name: Terraform Apply

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - terraform/**

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"
  ACCESS_TOKEN: ${{ secrets.MYPAT }}

jobs:
  terraform_apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        run: |
          PR_NUMBER=${{ github.event.number }}
          HEAD_SHA=$(gh api repos/Oddjob62/terrraform_actions/pulls/$PR_NUMBER | jq -r '.head.sha')
          RUN_ID=$(gh api repos/Oddjob62/terrraform_actions/commits/$HEAD_SHA/check-runs | jq -r '.check_runs | .[] | select(.name | contains("plan")) | .id ')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT
          echo "PR Number: $PR_NUMBER"
          echo "Run ID: $RUN_ID"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        


      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact_token: ${{ secrets.MYPAT }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
          run_id: ${{ steps.pr-id.outputs.RUN_ID }}
