name: Terraform Apply

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - terraform/**

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"
  ACCESS_TOKEN: ${{ secrets.MYPAT }}

jobs:
  terraform_apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          # PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR_NUMBER=${{ github.event.number }}
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

          echo $GITHUB_REF
          echo "PR Event number ${{ github.event.number }}"
          echo $PR_NUMBER
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Run ID: ${{ github.run_id }}""

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GH_TOKEN }}
          artifact_token: ${{ secrets.MYPAT }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
