name: Terraform Plan

on:
  pull_request:
    paths:
     - terraform/**

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo $PR_NUMBER

      - name: Terraform Plan
        uses: ./.github/plan
        with:
          terraform_directory: "terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
